export default {
  severity: { informational: 'Informational', low: 'Low', medium: 'Medium', high: 'High', critical: 'Critical' },
  confidence: { low: 'Low', medium: 'Medium', high: 'High' },
  status: { new: 'New', investigating: 'Investigating', acknowledged: 'Acknowledged', resolved: 'Resolved', ignored: 'Ignored' },
  filters: {
    allSeverity: 'All severities', status: 'Status', allStatus: 'All statuses', category: 'Category', allCategories: 'All categories', rule: 'Rule', allRules: 'All rules', more: 'More filters', entityType: 'Entity type', entityKey: 'Entity key', exactType: 'Exact type', exactKey: 'Exact key', from: 'From', to: 'To', ariaLabel: 'Detection severity filters',
  },
  table: {
    time: 'Time', detection: 'Detection', entity: 'Entity', severity: 'Severity', confidence: 'Confidence', status: 'Status', categoryUnavailable: 'category unavailable', conditionInactive: 'Condition inactive', loadError: 'Detections could not be loaded. Try again.', loading: 'Loading detections', empty: 'No detections under current coverage', emptyDescription: 'Detections appear only when an enabled rule has sufficient corroborating evidence. Factual Events remain available separately.', ariaLabel: 'Explainable detections',
  },
  drawer: {
    title: 'Detection details', detection: 'Detection', titleLabel: 'Title', description: 'Description', severity: 'Severity', confidence: 'Confidence', status: 'Status', whyFlagged: 'Why this was flagged', whatHappened: 'What happened', ruleExplanation: 'Rule explanation', severityRationale: 'Severity rationale', confidenceRationale: 'Confidence rationale', evidence: 'Evidence', evidenceLoadError: 'Evidence could not be loaded. Try again.', viewEvent: 'View event', noEvidence: 'No evidence records were returned. This detection should be reviewed as incomplete.', entityAndBaseline: 'Entity and baseline', entityType: 'Entity type', entityKey: 'Entity key', knownInBaseline: 'Known in baseline', comparedBaseline: 'Compared with the active baseline', noComparableBaseline: 'No comparable baseline reference', baselineId: 'Baseline ID', notApplicable: 'Not applicable', rule: 'Rule', ruleId: 'Rule ID', ruleName: 'Rule name', version: 'Version', category: 'Category', unavailable: 'Unavailable', timeline: 'Timeline', firstDetected: 'First detected', lastDetected: 'Last detected', occurrences: 'Occurrences', condition: 'Condition', active: 'Active', inactive: 'No longer active', recommendedAction: 'Recommended action', provenance: 'Provenance', provenanceCopy: 'Each evidence record links to its original factual Security Event. Those events retain their collector, baseline context, timestamps and append-only history.', actionsAriaLabel: 'Detection status actions', investigate: 'Investigate', acknowledge: 'Acknowledge', resolve: 'Resolve', ignore: 'Ignore',
  },
  unavailable: 'Unavailable',
  entityTypes: { process: 'Process', executable: 'Executable', process_pattern: 'Process pattern', process_relationship: 'Process relationship', network_destination: 'Network destination', service: 'Service', network_configuration: 'Network configuration' },
  collectorSources: { system: 'System', processes: 'Processes', connections: 'Connections', services: 'Services', network: 'Network' },
  evidenceTypes: { executable_identity: 'Executable identity', executed_process: 'Executed process', process_relationship: 'Process relationship', network_destination: 'Network destination', service_configuration: 'Service configuration', service_change: 'Service change', gateway_configuration: 'Gateway configuration', dns_configuration: 'DNS configuration' },
  evidenceLabels: { unsignedTemporaryExecutable: 'Unsigned temporary executable', executedProcessPattern: 'Executed process pattern', newParentChildRelationship: 'New parent-child relationship', newAssociatedDestination: 'New associated destination', newAutomaticUserWritableService: 'New automatic user-writable-path service', serviceStartupChanged: 'Service startup changed', serviceBinaryChanged: 'Service binary changed', serviceAccountChanged: 'Service account changed', gatewayChanged: 'Gateway changed', dnsResolversChanged: 'DNS resolvers changed' },
  evidenceFields: { executableKey: 'Executable key', processKey: 'Process key', parentKey: 'Parent key', childKey: 'Child key', childExecutableKey: 'Child executable key', parentExecutableKey: 'Parent executable key', path: 'Path', parentPath: 'Parent path', childPath: 'Child path', signatureStatus: 'Signature status', pid: 'PID', parentPid: 'Parent PID', runtimePid: 'Runtime PID', process: 'Process', parentProcess: 'Parent process', parent: 'Parent', child: 'Child', processName: 'Process name', user: 'User', company: 'Company', signer: 'Signer', architecture: 'Architecture', fileSize: 'File size', fileModifiedAt: 'File modified at', firstObserved: 'First observed', firstObservedMissing: 'First observation missing', localAddress: 'Local address', localPort: 'Local port', remoteAddress: 'Remote address', remoteIp: 'Remote IP', remotePort: 'Remote port', protocol: 'Protocol', ipVersion: 'IP version', association: 'Association', serviceKey: 'Service key', serviceName: 'Service name', displayName: 'Display name', startupType: 'Startup type', lastKnownStartupType: 'Last known startup type', binaryPath: 'Binary path', account: 'Account', status: 'Status', field: 'Field', before: 'Before', after: 'After', beforeAddress: 'Previous address', afterAddress: 'New address', beforeInterface: 'Previous interface', afterInterface: 'New interface', beforeMetric: 'Previous metric', afterMetric: 'New metric', interfaceType: 'Interface type', primaryInterfaceKey: 'Primary interface key', gateway: 'Gateway', dnsServers: 'DNS servers', comparison: 'Comparison', baselineVersion: 'Baseline version', correlationCycle: 'Correlation cycle' },
  presentations: {
    'EDY-PROC-001': { title: 'New unsigned executable ran from a temporary path', summary: "An executable absent from the baseline ran from the user's local temporary directory, and Windows reported it as unsigned.", whatHappened: "A new unsigned executable was executed from the user's local temporary directory.", whyFlagged: 'The executable was absent from the baseline, was actually running, was reported as unsigned, and used a narrowly defined temporary path.', severityReason: 'Multiple local facts are present, but legitimate installers and development tools remain plausible.', confidenceReason: 'Path, signature state, execution and baseline novelty are all present in one factual event.', guidance: { 0: 'Verify the executable origin and the software that created it', 1: 'Review its digital signature and parent process' } },
    'EDY-PROC-002': { title: 'New parent-child relationship launched an unsigned temporary executable', summary: 'A new process relationship and a new unsigned temporary executable were correlated in the same observation window.', whatHappened: "A previously unseen parent-child relationship launched a previously unseen unsigned executable from the user's temporary directory.", whyFlagged: 'The rule correlated the child path or executable identity across two factual events rather than relying on a process name alone.', severityReason: 'The relationship, execution context, temporary path and unsigned state corroborate each other; no maliciousness is asserted.', confidenceReason: 'Two independent factual event types identify the same child executable within sixty seconds.', guidance: { 0: 'Inspect the parent process and verify whether it belongs to an expected installer or updater', 1: 'Review the executable origin and signature before taking any action' } },
    'EDY-NET-001': { title: 'New unsigned temporary executable opened a new outbound destination', summary: "A new destination was associated with the same new unsigned executable running from the user's temporary directory.", whatHappened: 'A newly observed unsigned temporary executable initiated newly observed non-loopback network activity.', whyFlagged: 'The destination alone was not sufficient; the rule required associated process and executable context.', severityReason: 'Execution, signature, path and associated network activity provide corroboration, without external reputation claims.', confidenceReason: 'The process association and executable identity were correlated inside a sixty-second window.', guidance: { 0: 'Verify the executable origin and whether the destination is expected for the software', 1: 'Review the parent process and recent installation activity' } },
    'EDY-SVC-001': { title: 'New automatic service uses a binary from a user-writable path', summary: 'A newly observed automatic Windows service points to a user-writable application, downloads or desktop directory.', whatHappened: 'A new automatic service was configured to run a binary from a user-writable directory.', whyFlagged: 'A new service alone was insufficient; automatic startup, privileged account and an unambiguous user-writable executable path were required.', severityReason: 'Automatic startup, a user-writable binary path and a privileged service account are corroborated.', confidenceReason: 'The service identity, startup type and binary path are present in one successful SCM observation.', guidance: { 0: 'Review the service installation source and binary path', 1: 'Verify whether a recent trusted installer created the service' } },
    'EDY-SVC-002': { title: 'Multiple persistent service properties changed together', summary: 'At least two baseline service properties changed for the same service within forty-five seconds.', whatHappened: 'Multiple persistent properties of a baseline service changed together.', whyFlagged: 'The rule required at least two independent service configuration changes and never inferred intent from a single change.', severityReason: 'A binary-path change combined with another persistent property justifies investigation.', confidenceReason: 'Distinct factual service-change events identify the same service inside one correlation window.', guidance: { 0: 'Review the software or administrator action that modified the service', 1: 'Compare the new binary, startup and account settings with expected configuration' } },
    'EDY-NET-002': { title: 'Gateway and DNS changed without a primary-route transition', summary: 'The default gateway and DNS resolver set changed together while the primary route identity remained stable.', whatHappened: 'Gateway and DNS configuration changed together without evidence of a primary interface transition.', whyFlagged: 'A single DNS, gateway or route change cannot trigger this rule.', severityReason: 'The combined change warrants review, but VPN, DHCP and managed-network changes remain common legitimate causes.', confidenceReason: 'Two independent network configuration facts occurred in the same collection window.', guidance: { 0: 'Confirm whether Wi-Fi, VPN, DHCP or administrator configuration changed', 1: 'Compare the gateway and DNS values with the expected network' } },
  },
} as const
