export default {
  panel: { title: 'Security Score', subtitle: 'Observed posture under current coverage', ariaLabel: 'Security Score {{score}} out of 100. {{state}}. View breakdown.', viewBreakdown: 'View score breakdown', baseline: 'Baseline {{status}}', active_one: '{{formattedCount}} active', active_other: '{{formattedCount}} active', detectionsImpact: 'Detections {{value}}', vulnerabilitiesImpact: 'Vulnerabilities {{value}}', attention_one: '{{formattedCount}} item needs attention', attention_other: '{{formattedCount}} items need attention' },
  state: { available: 'Available', limited: 'Limited coverage', limitedAnalysis: 'Analysis has limited coverage', unavailable: 'Score unavailable' },
  labels: { excellent: 'Excellent', good: 'Good', attention: 'Attention', elevatedRisk: 'Elevated Risk', observedPosture: 'Observed posture' },
  availability: {
    noScoreTitle: 'Security Score unavailable', noScoreDetail: 'Security analysis has not returned a score state.', limitedDetail: 'Some vulnerability evaluations are still pending.', unavailableDetail: 'Required baseline, collection or detection data is unavailable.', invalidTitle: 'Security Score unavailable', invalidDetail: 'The engine returned an invalid score value.', activeDetections_one: '{{formattedCount}} active detection under current coverage', activeDetections_other: '{{formattedCount}} active detections under current coverage',
  },
  reasons: { noBaseline: 'Score unavailable — no behavioral baseline exists', learning: 'Score unavailable — baseline still learning', stale: 'Score unavailable — baseline coverage is stale', error: 'Score unavailable — baseline is in Error', notReady: 'Score unavailable — baseline is not ready', noRules: 'Score unavailable — no detection rules are enabled', incompleteCoverage: 'Score unavailable — required collector coverage is incomplete', vulnerabilityUpdating: 'Limited coverage — Vulnerability Intelligence is updating' },
  drawer: { title: 'Security Score breakdown', score: 'Security Score', why: 'Why this score?', baseScore: 'Base score', baseScoreDetail: 'Starting point before current penalties', detections: 'Detections', detectionsDetail_one: '{{formattedCount}} active detection', detectionsDetail_other: '{{formattedCount}} active detections', vulnerabilities: 'Vulnerabilities', vulnerabilitiesDetail_one: '{{formattedCount}} confirmed CVE', vulnerabilitiesDetail_other: '{{formattedCount}} confirmed CVEs', confidence: '{{confidence}} confidence', finalScore: 'Final score', formulaShort: 'Formula v{{version}}', coverage: 'Coverage', collectorCoverage: 'Module coverage', detectionInput: 'Detection input', activeDetections: 'Active detections', highestSeverity: 'Highest severity', none: 'None', formula: 'Technical details', formulaVersion: 'Score formula version', calculated: 'Calculated', notCalculated: 'Not calculated', observablePosture: 'The Security Score represents the device’s observable posture based on the modules and coverage currently available.', disclaimer: 'This score describes observable posture out of 100. It is not a percentage guarantee that the device is secure or insecure.' },
  coverageStatus: { healthy: 'Healthy', available: 'Available', degraded: 'Degraded', failed: 'Failed', unavailable: 'Unavailable' },
  coverageDetail: { healthy: 'Collection is available.', available: 'Collection is available.', degraded: 'Collection is partially available.', failed: 'Collection is unavailable.', unavailable: 'Coverage is unavailable.' },
  coverageComponent: { system: 'System', processes: 'Processes', connections: 'Connections', services: 'Services', 'detection-engine': 'Detection Engine' },
  vulnerability: {
    category: 'Vulnerability risk', productRisk: 'Risk by canonical product', impact: 'Score impact', included: 'Confirmed CVEs with high matching confidence', possibleNoImpact: 'Possible CVEs are shown for review and do not affect the score', kevAttention: 'CISA KEV prioritizes an already confirmed match; it does not confirm the software-to-CVE relationship', coverage: 'Software identity coverage', coverageBasis: 'Coverage proxy by software record', notMappable: 'Not mappable (excluded from eligible coverage)',
    states: { complete: 'Complete', limited: 'Limited', updating: 'Updating', unavailable: 'Unavailable', not_applicable: 'Not applicable' },
  },
  product: { openAria: 'Open risk details for {{product}}', confirmed_one: '{{formattedCount}} confirmed CVE', confirmed_other: '{{formattedCount}} confirmed CVEs', possible_one: '{{formattedCount}} possible match', possible_other: '{{formattedCount}} possible matches', kev_one: '{{formattedCount}} KEV', kev_other: '{{formattedCount}} KEVs', possibleImpactZero: 'Possible: score impact 0', none: 'No confirmed product risk affects the current score.' },
  coverage: { totalSoftware: 'Total software', eligible: 'Eligible', resolved: 'Resolved identities', ambiguous: 'Ambiguous', unresolved: 'Unresolved eligible', notMappable: 'Not mappable', pending: 'Pending evaluations', denominatorNote: 'Not mappable software is reported separately and excluded from the eligible coverage denominator. Software counts are not CVE counts.' },
  productDetail: { title: 'Product risk details', back: 'Back to score breakdown', product: 'Canonical product risk', impact: 'Score impact {{value}}', knownExploited: 'Known exploited vulnerability', summary: 'Risk summary', versions: 'Installed version', confirmed: 'Confirmed vulnerabilities', possible: 'Possible matches', highestCvss: 'Highest CVSS', kev: 'CISA KEV', scoreImpact: 'Security Score impact', confirmedCves: 'Confirmed CVEs', possibleCves: 'Possible matches', possibleMatch: 'Possible match', possibleImpactZero: 'Impact on Security Score: 0', evidence: 'Evidence versions', matchingEngine: 'Matching engine', identityResolver: 'Identity resolver', evaluated: 'Evaluated', openInventory: 'Open product in Software Inventory' },
  baselineStatus: { not_initialized: 'not initialized', learning: 'learning', ready: 'ready', stale: 'stale', error: 'error' },
} as const
