export default {
  severity: { informational: 'Informativa', low: 'Baixa', medium: 'Média', high: 'Alta', critical: 'Crítica' },
  confidence: { low: 'Baixa', medium: 'Média', high: 'Alta' },
  status: { new: 'Nova', investigating: 'Em investigação', acknowledged: 'Reconhecida', resolved: 'Resolvida', ignored: 'Ignorada' },
  filters: {
    allSeverity: 'Todas as severidades', status: 'Status', allStatus: 'Todos os status', category: 'Categoria', allCategories: 'Todas as categorias', rule: 'Regra', allRules: 'Todas as regras', more: 'Mais filtros', entityType: 'Tipo de entidade', entityKey: 'Chave da entidade', exactType: 'Tipo exato', exactKey: 'Chave exata', from: 'De', to: 'Até', ariaLabel: 'Filtros de severidade das detecções',
  },
  table: {
    time: 'Horário', detection: 'Detecção', entity: 'Entidade', severity: 'Severidade', confidence: 'Confiança', status: 'Status', categoryUnavailable: 'categoria indisponível', conditionInactive: 'Condição inativa', loadError: 'Não foi possível carregar as detecções. Tente novamente.', loading: 'Carregando detecções', empty: 'Nenhuma detecção na cobertura atual', emptyDescription: 'As detecções aparecem apenas quando uma regra habilitada possui evidências corroborantes suficientes. Os eventos de segurança factuais permanecem disponíveis separadamente.', ariaLabel: 'Detecções explicáveis',
  },
  drawer: {
    title: 'Detalhes da detecção', detection: 'Detecção', titleLabel: 'Título', description: 'Descrição', severity: 'Severidade', confidence: 'Confiança', status: 'Status', whyFlagged: 'Por que isso foi sinalizado', whatHappened: 'O que aconteceu', ruleExplanation: 'Explicação da regra', severityRationale: 'Justificativa da severidade', confidenceRationale: 'Justificativa da confiança', evidence: 'Evidências', evidenceLoadError: 'Não foi possível carregar as evidências. Tente novamente.', viewEvent: 'Ver evento', noEvidence: 'Nenhum registro de evidência foi retornado. Esta detecção deve ser analisada como incompleta.', entityAndBaseline: 'Entidade e baseline', entityType: 'Tipo de entidade', entityKey: 'Chave da entidade', knownInBaseline: 'Conhecida na baseline', comparedBaseline: 'Comparada com a baseline ativa', noComparableBaseline: 'Sem referência de baseline comparável', baselineId: 'ID da baseline', notApplicable: 'Não aplicável', rule: 'Regra', ruleId: 'ID da regra', ruleName: 'Nome da regra', version: 'Versão', category: 'Categoria', unavailable: 'Indisponível', timeline: 'Linha do tempo', firstDetected: 'Detectada pela primeira vez', lastDetected: 'Detectada pela última vez', occurrences: 'Ocorrências', condition: 'Condição', active: 'Ativa', inactive: 'Não está mais ativa', recommendedAction: 'Ação recomendada', provenance: 'Proveniência', provenanceCopy: 'Cada registro de evidência referencia o evento de segurança factual que lhe deu origem. Esses eventos preservam o coletor, o contexto da baseline, os horários e um histórico somente de acréscimo, cujos registros não são alterados.', actionsAriaLabel: 'Ações de status da detecção', investigate: 'Investigar', acknowledge: 'Reconhecer', resolve: 'Resolver', ignore: 'Ignorar',
  },
  unavailable: 'Indisponível',
  entityTypes: { process: 'Processo', executable: 'Executável', process_pattern: 'Padrão de processo', process_relationship: 'Relação de processos', network_destination: 'Destino de rede', service: 'Serviço', network_configuration: 'Configuração de rede' },
  collectorSources: { system: 'Sistema', processes: 'Processos', connections: 'Conexões', services: 'Serviços', network: 'Rede' },
  evidenceTypes: { executable_identity: 'Identidade do executável', executed_process: 'Processo executado', process_relationship: 'Relação de processos', network_destination: 'Destino de rede', service_configuration: 'Configuração do serviço', service_change: 'Alteração do serviço', gateway_configuration: 'Configuração do gateway', dns_configuration: 'Configuração de DNS' },
  evidenceLabels: { unsignedTemporaryExecutable: 'Executável temporário não assinado', executedProcessPattern: 'Padrão de processo executado', newParentChildRelationship: 'Nova relação pai-filho', newAssociatedDestination: 'Novo destino associado', newAutomaticUserWritableService: 'Novo serviço automático em caminho gravável pelo usuário', serviceStartupChanged: 'Inicialização do serviço alterada', serviceBinaryChanged: 'Binário do serviço alterado', serviceAccountChanged: 'Conta do serviço alterada', gatewayChanged: 'Gateway alterado', dnsResolversChanged: 'Resolvedores DNS alterados' },
  evidenceFields: { executableKey: 'Chave do executável', processKey: 'Chave do processo', parentKey: 'Chave do processo pai', childKey: 'Chave do processo filho', childExecutableKey: 'Chave do executável filho', parentExecutableKey: 'Chave do executável pai', path: 'Caminho', parentPath: 'Caminho do processo pai', childPath: 'Caminho do processo filho', signatureStatus: 'Status da assinatura', pid: 'PID', parentPid: 'PID do processo pai', runtimePid: 'PID em execução', process: 'Processo', parentProcess: 'Processo pai', parent: 'Processo pai', child: 'Processo filho', processName: 'Nome do processo', user: 'Usuário', company: 'Empresa', signer: 'Signatário', architecture: 'Arquitetura', fileSize: 'Tamanho do arquivo', fileModifiedAt: 'Arquivo modificado em', firstObserved: 'Primeira observação', firstObservedMissing: 'Primeira observação ausente', localAddress: 'Endereço local', localPort: 'Porta local', remoteAddress: 'Endereço remoto', remoteIp: 'IP remoto', remotePort: 'Porta remota', protocol: 'Protocolo', ipVersion: 'Versão IP', association: 'Associação', serviceKey: 'Chave do serviço', serviceName: 'Nome do serviço', displayName: 'Nome de exibição', startupType: 'Tipo de inicialização', lastKnownStartupType: 'Último tipo de inicialização conhecido', binaryPath: 'Caminho do binário', account: 'Conta', status: 'Status', field: 'Campo', before: 'Antes', after: 'Depois', beforeAddress: 'Endereço anterior', afterAddress: 'Novo endereço', beforeInterface: 'Interface anterior', afterInterface: 'Nova interface', beforeMetric: 'Métrica anterior', afterMetric: 'Nova métrica', interfaceType: 'Tipo de interface', primaryInterfaceKey: 'Chave da interface primária', gateway: 'Gateway', dnsServers: 'Servidores DNS', comparison: 'Comparação', baselineVersion: 'Versão da baseline', correlationCycle: 'Ciclo de correlação' },
  presentations: {
    'EDY-PROC-001': { title: 'Novo executável não assinado executado a partir de caminho temporário', summary: 'Um executável ausente da baseline foi executado no diretório temporário local do usuário, e o Windows o identificou como não assinado.', whatHappened: 'Um novo executável não assinado foi executado no diretório temporário local do usuário.', whyFlagged: 'O executável estava ausente da baseline, estava realmente em execução, foi identificado como não assinado e utilizava um caminho temporário definido de forma restrita.', severityReason: 'Há vários fatos locais, mas instaladores e ferramentas de desenvolvimento legítimos continuam sendo explicações plausíveis.', confidenceReason: 'Caminho, estado da assinatura, execução e novidade em relação à baseline estão presentes em um mesmo evento factual.', guidance: { 0: 'Verifique a origem do executável e o software que o criou', 1: 'Analise a assinatura digital e o processo pai' } },
    'EDY-PROC-002': { title: 'Nova relação pai-filho iniciou um executável temporário não assinado', summary: 'Uma nova relação de processos e um novo executável temporário não assinado foram correlacionados na mesma janela de observação.', whatHappened: 'Uma relação pai-filho até então não observada iniciou um executável não assinado, também novo, no diretório temporário do usuário.', whyFlagged: 'A regra correlacionou o caminho do filho ou a identidade do executável em dois eventos factuais, sem depender apenas do nome do processo.', severityReason: 'A relação, o contexto de execução, o caminho temporário e o estado não assinado se corroboram; nenhuma intenção maliciosa é afirmada.', confidenceReason: 'Dois tipos independentes de evento factual identificam o mesmo executável filho em até sessenta segundos.', guidance: { 0: 'Inspecione o processo pai e verifique se ele pertence a um instalador ou atualizador esperado', 1: 'Analise a origem e a assinatura do executável antes de tomar qualquer ação' } },
    'EDY-NET-001': { title: 'Novo executável temporário não assinado abriu um novo destino de saída', summary: 'Um novo destino foi associado ao mesmo executável novo e não assinado em execução no diretório temporário do usuário.', whatHappened: 'Um executável temporário não assinado recém-observado iniciou atividade de rede não loopback também recém-observada.', whyFlagged: 'O destino isolado não foi suficiente; a regra exigiu o contexto associado do processo e do executável.', severityReason: 'Execução, assinatura, caminho e atividade de rede associada fornecem corroboração, sem alegações de reputação externa.', confidenceReason: 'A associação do processo e a identidade do executável foram correlacionadas em uma janela de sessenta segundos.', guidance: { 0: 'Verifique a origem do executável e se o destino é esperado para o software', 1: 'Analise o processo pai e atividades recentes de instalação' } },
    'EDY-SVC-001': { title: 'Novo serviço automático usa binário em caminho gravável pelo usuário', summary: 'Um serviço automático do Windows recém-observado aponta para um diretório de aplicativo, downloads ou área de trabalho gravável pelo usuário.', whatHappened: 'Um novo serviço automático foi configurado para executar um binário de um diretório gravável pelo usuário.', whyFlagged: 'Um serviço novo isolado não foi suficiente; foram exigidos inicialização automática, conta privilegiada e caminho de executável inequívoco e gravável pelo usuário.', severityReason: 'Inicialização automática, caminho do binário gravável pelo usuário e conta de serviço privilegiada são corroborados.', confidenceReason: 'Identidade do serviço, tipo de inicialização e caminho do binário estão presentes em uma observação bem-sucedida do SCM.', guidance: { 0: 'Analise a origem da instalação do serviço e o caminho do binário', 1: 'Verifique se um instalador confiável recente criou o serviço' } },
    'EDY-SVC-002': { title: 'Várias propriedades persistentes do serviço foram alteradas em conjunto', summary: 'Ao menos duas propriedades do mesmo serviço da baseline mudaram em uma janela de quarenta e cinco segundos.', whatHappened: 'Várias propriedades persistentes de um serviço da baseline foram alteradas em conjunto.', whyFlagged: 'A regra exigiu pelo menos duas alterações independentes na configuração do serviço e nunca inferiu intenção a partir de uma única mudança.', severityReason: 'Uma alteração no caminho do binário combinada com outra propriedade persistente justifica investigação.', confidenceReason: 'Eventos factuais distintos de alteração de serviço identificam o mesmo serviço dentro de uma janela de correlação.', guidance: { 0: 'Analise o software ou a ação administrativa que modificou o serviço', 1: 'Compare as novas configurações de binário, inicialização e conta com a configuração esperada' } },
    'EDY-NET-002': { title: 'Gateway e DNS mudaram sem transição da rota primária', summary: 'O gateway padrão e o conjunto de resolvedores DNS mudaram em conjunto enquanto a identidade da rota primária permaneceu estável.', whatHappened: 'As configurações de gateway e DNS mudaram em conjunto sem evidência de transição da interface primária.', whyFlagged: 'Uma única alteração de DNS, gateway ou rota não pode acionar esta regra.', severityReason: 'A alteração combinada merece análise, mas VPN, DHCP e mudanças de rede gerenciada continuam sendo causas legítimas comuns.', confidenceReason: 'Dois fatos independentes de configuração de rede ocorreram na mesma janela de coleta.', guidance: { 0: 'Confirme se houve alteração de Wi-Fi, VPN, DHCP ou configuração administrativa', 1: 'Compare os valores de gateway e DNS com a rede esperada' } },
  },
} as const
