export default {
  panel: { title: 'Pontuação de Segurança', subtitle: 'Postura observada na cobertura atual', ariaLabel: 'Pontuação de Segurança {{score}} de 100. {{state}}. Ver detalhamento.', viewBreakdown: 'Ver detalhamento da pontuação', baseline: 'Baseline {{status}}', active_one: '{{formattedCount}} ativa', active_other: '{{formattedCount}} ativas', detectionsImpact: 'Detecções {{value}}', vulnerabilitiesImpact: 'Vulnerabilidades {{value}}', attention_one: '{{formattedCount}} item requer atenção', attention_other: '{{formattedCount}} itens requerem atenção' },
  state: { available: 'Disponível', limited: 'Cobertura limitada', limitedAnalysis: 'Análise com cobertura limitada', unavailable: 'Pontuação indisponível' },
  labels: { excellent: 'Excelente', good: 'Boa', attention: 'Atenção', elevatedRisk: 'Risco elevado', observedPosture: 'Postura observada' },
  availability: {
    noScoreTitle: 'Pontuação de Segurança indisponível', noScoreDetail: 'A análise de segurança ainda não retornou um estado da pontuação.', limitedDetail: 'Algumas avaliações de vulnerabilidade ainda estão pendentes.', unavailableDetail: 'Os dados necessários de baseline, coleta ou detecção estão indisponíveis.', invalidTitle: 'Pontuação de Segurança indisponível', invalidDetail: 'O mecanismo retornou um valor de pontuação inválido.', activeDetections_one: '{{formattedCount}} detecção ativa na cobertura atual', activeDetections_other: '{{formattedCount}} detecções ativas na cobertura atual',
  },
  reasons: { noBaseline: 'Pontuação indisponível — não existe baseline comportamental', learning: 'Pontuação indisponível — a baseline ainda está aprendendo', stale: 'Pontuação indisponível — a cobertura da baseline está desatualizada', error: 'Pontuação indisponível — a baseline está em Erro', notReady: 'Pontuação indisponível — a baseline não está pronta', noRules: 'Pontuação indisponível — nenhuma regra de detecção está habilitada', incompleteCoverage: 'Pontuação indisponível — a cobertura dos coletores obrigatórios está incompleta', vulnerabilityUpdating: 'Cobertura limitada — a Inteligência de Vulnerabilidades está atualizando' },
  drawer: { title: 'Detalhamento da Pontuação de Segurança', score: 'Pontuação de Segurança', why: 'Por que esta pontuação?', baseScore: 'Pontuação base', baseScoreDetail: 'Ponto inicial antes das penalidades atuais', detections: 'Detecções', detectionsDetail_one: '{{formattedCount}} detecção ativa', detectionsDetail_other: '{{formattedCount}} detecções ativas', vulnerabilities: 'Vulnerabilidades', vulnerabilitiesDetail_one: '{{formattedCount}} CVE confirmada', vulnerabilitiesDetail_other: '{{formattedCount}} CVEs confirmadas', confidence: 'confiança {{confidence}}', finalScore: 'Pontuação final', formulaShort: 'Fórmula v{{version}}', coverage: 'Cobertura', collectorCoverage: 'Cobertura dos módulos', detectionInput: 'Entrada de detecções', activeDetections: 'Detecções ativas', highestSeverity: 'Maior severidade', none: 'Nenhuma', formula: 'Detalhes técnicos', formulaVersion: 'Versão da fórmula da pontuação', calculated: 'Calculada em', notCalculated: 'Não calculada', observablePosture: 'A Pontuação de Segurança representa a postura observável do dispositivo com base nos módulos e na cobertura atualmente disponíveis.', disclaimer: 'Esta pontuação descreve a postura observável em uma escala de 100. Ela não é uma garantia percentual de que o dispositivo está seguro ou inseguro.' },
  coverageStatus: { healthy: 'Saudável', available: 'Disponível', degraded: 'Degradada', failed: 'Com falha', unavailable: 'Indisponível' },
  coverageDetail: { healthy: 'A coleta está disponível.', available: 'A coleta está disponível.', degraded: 'A coleta está parcialmente disponível.', failed: 'A coleta está indisponível.', unavailable: 'A cobertura está indisponível.' },
  coverageComponent: { system: 'Sistema', processes: 'Processos', connections: 'Conexões', services: 'Serviços', 'detection-engine': 'Mecanismo de Detecção' },
  vulnerability: {
    category: 'Risco de vulnerabilidades', productRisk: 'Risco por produto canônico', impact: 'Impacto na pontuação', included: 'CVEs confirmadas com alta confiança de correspondência', possibleNoImpact: 'CVEs possíveis são exibidas para revisão e não afetam a pontuação', kevAttention: 'O CISA KEV prioriza uma correspondência já confirmada; ele não confirma a relação entre software e CVE', coverage: 'Cobertura de identidade de software', coverageBasis: 'Proxy de cobertura por registro de software', notMappable: 'Não mapeável (excluído da cobertura elegível)',
    states: { complete: 'Completa', limited: 'Limitada', updating: 'Atualizando', unavailable: 'Indisponível', not_applicable: 'Não aplicável' },
  },
  product: { openAria: 'Abrir detalhes de risco de {{product}}', confirmed_one: '{{formattedCount}} CVE confirmada', confirmed_other: '{{formattedCount}} CVEs confirmadas', possible_one: '{{formattedCount}} correspondência possível', possible_other: '{{formattedCount}} correspondências possíveis', kev_one: '{{formattedCount}} KEV', kev_other: '{{formattedCount}} KEVs', possibleImpactZero: 'Possível: impacto 0', none: 'Nenhum risco confirmado de produto afeta a pontuação atual.' },
  coverage: { totalSoftware: 'Total de softwares', eligible: 'Elegíveis', resolved: 'Identidades resolvidas', ambiguous: 'Ambíguas', unresolved: 'Elegíveis não resolvidos', notMappable: 'Não mapeáveis', pending: 'Avaliações pendentes', denominatorNote: 'Softwares não mapeáveis são informados separadamente e ficam fora do denominador de cobertura elegível. Quantidades de software não são quantidades de CVEs.' },
  productDetail: { title: 'Detalhes do risco do produto', back: 'Voltar ao detalhamento da pontuação', product: 'Risco do produto canônico', impact: 'Impacto na pontuação {{value}}', knownExploited: 'Vulnerabilidade com exploração conhecida', summary: 'Resumo do risco', versions: 'Versão instalada', confirmed: 'Vulnerabilidades confirmadas', possible: 'Correspondências possíveis', highestCvss: 'Maior CVSS', kev: 'CISA KEV', scoreImpact: 'Impacto na Pontuação de Segurança', confirmedCves: 'CVEs confirmadas', possibleCves: 'Correspondências possíveis', possibleMatch: 'Correspondência possível', possibleImpactZero: 'Impacto na Pontuação de Segurança: 0', evidence: 'Versões das evidências', matchingEngine: 'Mecanismo de correspondência', identityResolver: 'Resolver de identidade', evaluated: 'Avaliado em', openInventory: 'Abrir produto no Inventário de Software' },
  baselineStatus: { not_initialized: 'não inicializada', learning: 'aprendendo', ready: 'pronta', stale: 'desatualizada', error: 'com erro' },
} as const
