export default {
  panel: { title: 'Pontuação de Segurança', subtitle: 'Postura observada na cobertura atual', ariaLabel: 'Pontuação de Segurança {{score}} de 100. Ver detalhamento.', viewBreakdown: 'Ver detalhamento da pontuação', baseline: 'Baseline {{status}}', active_one: '{{formattedCount}} ativa', active_other: '{{formattedCount}} ativas' },
  state: { available: 'Disponível', limited: 'Cobertura limitada', unavailable: 'Pontuação indisponível' },
  labels: { excellent: 'Excelente', good: 'Boa', attention: 'Atenção', elevatedRisk: 'Risco elevado', observedPosture: 'Postura observada' },
  availability: {
    noScoreTitle: 'Pontuação de Segurança indisponível', noScoreDetail: 'A análise de segurança ainda não retornou um estado da pontuação.', limitedDetail: 'A cobertura mínima da pontuação não está disponível no momento.', unavailableDetail: 'Os dados necessários de baseline, coleta ou detecção estão indisponíveis.', invalidTitle: 'Pontuação de Segurança indisponível', invalidDetail: 'O mecanismo retornou um valor de pontuação inválido.', activeDetections_one: '{{formattedCount}} detecção ativa na cobertura atual', activeDetections_other: '{{formattedCount}} detecções ativas na cobertura atual',
  },
  reasons: { noBaseline: 'Pontuação indisponível — não existe baseline comportamental', learning: 'Pontuação indisponível — a baseline ainda está aprendendo', stale: 'Pontuação indisponível — a cobertura da baseline está desatualizada', error: 'Pontuação indisponível — a baseline está em Erro', notReady: 'Pontuação indisponível — a baseline não está pronta', noRules: 'Pontuação indisponível — nenhuma regra de detecção está habilitada', incompleteCoverage: 'Pontuação indisponível — a cobertura dos coletores obrigatórios está incompleta' },
  drawer: { title: 'Detalhamento da Pontuação de Segurança', score: 'Pontuação', why: 'Por que esta pontuação?', baseScore: 'Pontuação base', baseScoreDetail: 'Ponto inicial antes das penalidades das detecções ativas', confidence: 'confiança {{confidence}}', finalScore: 'Pontuação final', formulaShort: 'Fórmula v{{version}}', coverage: 'Cobertura', detectionInput: 'Entrada de detecções', activeDetections: 'Detecções ativas', highestSeverity: 'Maior severidade', none: 'Nenhuma', formula: 'Fórmula', formulaVersion: 'Versão da fórmula', calculated: 'Calculada em', notCalculated: 'Não calculada', disclaimer: 'Esta é uma pontuação da postura observada na cobertura atual do Sentinel, não uma garantia percentual de segurança.' },
  coverageStatus: { healthy: 'Saudável', available: 'Disponível', degraded: 'Degradada', failed: 'Com falha', unavailable: 'Indisponível' },
  coverageDetail: { healthy: 'A coleta está disponível.', available: 'A coleta está disponível.', degraded: 'A coleta está parcialmente disponível.', failed: 'A coleta está indisponível.', unavailable: 'A cobertura está indisponível.' },
  coverageComponent: { system: 'Sistema', processes: 'Processos', connections: 'Conexões', services: 'Serviços', 'detection-engine': 'Mecanismo de Detecção' },
  baselineStatus: { not_initialized: 'não inicializada', learning: 'aprendendo', ready: 'pronta', stale: 'desatualizada', error: 'com erro' },
} as const
